"""
generate_data_dictionary.py
----------------------------
Generates docs/data_dictionary.xlsx — a plain-English explanation of every
column in the final referral fraud report, written for a non-technical
reader (e.g. a Marketing Manager), per the spec's Documentation requirement.

Run once to (re)generate the file:
    python docs/generate_data_dictionary.py
"""

from pathlib import Path

from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

OUTPUT_PATH = Path(__file__).resolve().parent / "data_dictionary.xlsx"

# (Column Name, Data Type, Plain-English Description, Notes / Constraints)
COLUMNS = [
    ("referral_details_id", "Number",
     "A unique row number for this report. Row 1 is the first referral, row 2 the second, and so on.",
     "Generated by this report — not from the original source data."),

    ("referral_id", "Text",
     "A unique code identifying this specific referral.",
     "Always present."),

    ("referral_source", "Text",
     "How this referral was submitted — e.g. the new member signed up online themselves ('User Sign Up'), "
     "was linked to an existing draft transaction ('Draft Transaction'), or came from a sales lead ('Lead').",
     "Always present."),

    ("referral_source_category", "Text",
     "A simplified version of referral_source: either 'Online' or 'Offline'.",
     "May show 'N/A' for a small number of Lead referrals where the original lead record could not be found."),

    ("referral_at", "Date & Time",
     "The date and time the referral was created, shown in the referrer's local time zone.",
     "Shown in local time where available; falls back to UTC (world standard time) if the referrer's "
     "home location couldn't be determined."),

    ("referrer_id", "Text",
     "A unique code identifying the existing member who made the referral (the 'referrer').",
     "May show 'N/A' if the referral is still pending and no referrer has been confirmed yet."),

    ("referrer_name", "Text",
     "The name of the referrer.",
     "Shown as an anonymized code, not a plain name, for privacy. May show 'N/A' if no referrer is on record."),

    ("referrer_phone_number", "Text",
     "The referrer's phone number.",
     "Shown as an anonymized code, not a plain number, for privacy. May show 'N/A' if not available."),

    ("referrer_homeclub", "Text",
     "The gym/club location the referrer belongs to.",
     "May show 'N/A' if not available."),

    ("referee_id", "Text",
     "A unique code identifying the new member being referred (the 'referee').",
     "Only populated when the referral came from a sales lead; otherwise 'N/A' (see referee_name/referee_phone instead)."),

    ("referee_name", "Text",
     "The name of the new member being referred.",
     "Shown as an anonymized code, not a plain name, for privacy. May show 'N/A' in rare cases."),

    ("referee_phone", "Text",
     "The new member's phone number.",
     "Shown as an anonymized code, not a plain number, for privacy."),

    ("referral_status", "Text",
     "The current outcome of the referral: 'Berhasil' (Successful), 'Menunggu' (Pending), "
     "or 'Tidak Berhasil' (Failed).",
     "Always present."),

    ("num_reward_days", "Number",
     "The number of membership days awarded to the referrer as a reward for this referral.",
     "Shown as 0 when no reward has been assigned to this referral."),

    ("transaction_id", "Text",
     "A unique code identifying the purchase transaction linked to this referral, if any.",
     "May show 'N/A' if no transaction has happened yet (e.g. referral still pending)."),

    ("transaction_status", "Text",
     "The status of the linked transaction, e.g. 'Paid'.",
     "Shows 'N/A' if there's no transaction, OR if a transaction_id is listed but no matching "
     "transaction record actually exists — the latter is a red flag investigated in is_business_logic_valid."),

    ("transaction_at", "Date & Time",
     "The date and time the linked transaction occurred, shown in local time.",
     "Shows 'N/A' if there's no linked transaction."),

    ("transaction_location", "Text",
     "The gym/club location where the transaction took place.",
     "Shows 'N/A' if there's no linked transaction."),

    ("transaction_type", "Text",
     "The type of transaction — e.g. 'New' (a brand-new membership) or 'Rejoin' (a returning member).",
     "Shows 'N/A' if there's no linked transaction. Only 'New' transactions count toward a valid reward."),

    ("updated_at", "Date & Time",
     "The date and time this referral record was last updated, shown in local time.",
     "Falls back to UTC (world standard time) if local time couldn't be determined."),

    ("reward_granted_at", "Date & Time",
     "The date and time the reward was actually given to the referrer, if it was.",
     "Shows 'N/A' if the reward was never granted — including cases where every other requirement "
     "was met but the payout never happened (see is_business_logic_valid)."),

    ("is_business_logic_valid", "Yes / No (TRUE / FALSE)",
     "Whether this referral reward passes our fraud-and-integrity checks. TRUE means the reward looks "
     "legitimate. FALSE means something about it doesn't add up and should be reviewed — for example: "
     "a reward was paid out for a referral that wasn't actually successful, the linked transaction doesn't "
     "exist in our payment records, the transaction happened before the referral was even made, or every "
     "requirement was met but the reward was never actually paid out to the referrer.",
     "This is the main column to filter on when reviewing potential referral fraud."),
]

FONT_NAME = "Arial"
HEADER_FILL = PatternFill(start_color="1F4E78", end_color="1F4E78", fill_type="solid")
HEADER_FONT = Font(name=FONT_NAME, size=11, bold=True, color="FFFFFF")
TITLE_FONT = Font(name=FONT_NAME, size=14, bold=True, color="1F4E78")
SUBTITLE_FONT = Font(name=FONT_NAME, size=10, italic=True, color="595959")
BODY_FONT = Font(name=FONT_NAME, size=10)
THIN_BORDER = Border(
    left=Side(style="thin", color="D9D9D9"),
    right=Side(style="thin", color="D9D9D9"),
    top=Side(style="thin", color="D9D9D9"),
    bottom=Side(style="thin", color="D9D9D9"),
)
ALT_ROW_FILL = PatternFill(start_color="F2F6FA", end_color="F2F6FA", fill_type="solid")


def build_workbook() -> Workbook:
    wb = Workbook()
    ws = wb.active
    ws.title = "Data Dictionary"

    # Title block
    ws["A1"] = "Referral Fraud Report — Data Dictionary"
    ws["A1"].font = TITLE_FONT
    ws["A2"] = "Explains every column in referral_fraud_report.csv in plain language. For business users."
    ws["A2"].font = SUBTITLE_FONT
    ws.merge_cells("A1:D1")
    ws.merge_cells("A2:D2")

    header_row = 4
    headers = ["Column Name", "Data Type", "What It Means", "Notes"]
    for col_idx, header in enumerate(headers, start=1):
        cell = ws.cell(row=header_row, column=col_idx, value=header)
        cell.font = HEADER_FONT
        cell.fill = HEADER_FILL
        cell.alignment = Alignment(horizontal="left", vertical="center", wrap_text=True)
        cell.border = THIN_BORDER

    for i, (name, dtype, description, notes) in enumerate(COLUMNS):
        row = header_row + 1 + i
        values = [name, dtype, description, notes]
        fill = ALT_ROW_FILL if i % 2 == 1 else None
        for col_idx, value in enumerate(values, start=1):
            cell = ws.cell(row=row, column=col_idx, value=value)
            cell.font = BODY_FONT
            cell.alignment = Alignment(horizontal="left", vertical="top", wrap_text=True)
            cell.border = THIN_BORDER
            if fill:
                cell.fill = fill

    # Column widths tuned for readability of wrapped text
    widths = {"A": 26, "B": 20, "C": 55, "D": 45}
    for col, width in widths.items():
        ws.column_dimensions[col].width = width

    # Row heights: give the two wide text columns room to wrap
    ws.row_dimensions[1].height = 22
    ws.row_dimensions[2].height = 16
    for i in range(len(COLUMNS)):
        ws.row_dimensions[header_row + 1 + i].height = 45

    ws.freeze_panes = f"A{header_row + 1}"
    ws.sheet_view.showGridLines = False

    return wb


if __name__ == "__main__":
    wb = build_workbook()
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    wb.save(OUTPUT_PATH)
    print(f"[WRITE] Data dictionary written to: {OUTPUT_PATH}")
    print(f"[INFO] {len(COLUMNS)} columns documented")